data:
  root_path: ${hydra:runtime.cwd}/data
  val_size: 0.2
  dataloader_num_wokers: 4
  batch_size: 128
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]
  size_h: 96
  size_w: 96
  num_classes: 2

model:
  in_feature: 3
  dropout: 0.3
  embedding_size: 128

train:
  learning_rate: 1e-3
  num_training_steps: 1000
  grad_accum_steps: 4
  accelerator: cpu
  devices: 1
  precision: 16-mixed
  val_check_interval: 1.0
  overfit_batches: 0
  num_sanity_val_steps: 4
  full_deterministic_mode: false
  benchmark: false
  gradient_clip_val: 1.0
  profiler:
  log_every_n_steps: 1
  batch_size_finder: false
  detect_anomaly: false

artifacts:
  experiment_name: example-experiment
  checkpoint:
    use: false
    dirpath: checkpoints
    filename: "{epoch:02d}-{val_loss:.4f}"
    monitor: val_loss
    save_top_k: 3
    every_n_train_steps:
    every_n_epochs: 1

callbacks:
  model_summary:
    max_depth: 1
  swa:
    use: false
    lrs: 1e-3
