defaults:
  - datasets: dogs_vs_cats
  - _self_
paths:
  data: ${hydra:runtime.cwd}/data
params:
  n_epochs: 20
  lr: 1e-3
  batch_size: 128
  embedding_size: 128
  in_feature: 3 # may be changed for future tasks
  num_classes: 2 # may be changed for future tasks
